name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - run: flutter pub get

      # خطوة pod install (على macOS)
      - run: |
          cd ios
          pod install || true
          cd ..

      - run: flutter build ipa --no-codesign

      - uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
