name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v3
        with:
          channel: stable

      - run: flutter pub get

      # هذه الخطوة ستنشئ Podfile تلقائيًا لو مش موجود
      - run: |
          cd ios
          flutter pub get
          pod install || true
          cd ..

      - run: flutter build ipa --no-codesign

      - uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa